### ISSUE TITLE
Dataset documentation

### ISSUE THREAD

**Issue by kkirchheim** [Jingkang50/OpenOOD#169]
Hi, thank you for your work on OpenOOD. 
I was unable to find out what the `ssb_hard` dataset is. Could you tell me? I could not find a direct reference to it in the paper or the 1.5 technical report. It might be a good idea to consider improving the projects documentation by adding some comments to the configuration files. 

Also, I could not find the `species` dataset subset with 10k classes (`ssb_hard` has 980, so it should be some other dataset). Is this dataset included in the download script? Or are you directly using the version provided by Hendrycks et al.? Because that one is quite large and difficult to download.

**Comment by zjysteven** [comment]
Hi @kkirchheim,

`SSB` is the OOD dataset curated in this [repo](https://github.com/sgvaze/osr_closed_set_all_you_need), and we did put detailed description of each selected OOD dataset in the appendix of our v1.5 report (there wasn't enough space in the main text).

For `species`, in v1 we randomly selected ~10000 images to ease the evaluation burden. In v1.5 we didn't include it because of the issue raised in [this work](https://arxiv.org/abs/2306.00826). Again, this part is discussed in Appendix A in our [v1.5 report](https://arxiv.org/pdf/2306.09301.pdf).

As for the documentation, I agree that it could be improved by having it somewhere in the repo, and having some feedbacks definitely helps. Would you let us know what would you expect from the documentation? E.g., descriptions of the benchmarked datasets and methods?

**Comment by kkirchheim** [comment]
Thank you for the quick response. Sorry for the points I missed in the report, I must have glanced over them. I was mainly looking at the code/configuration files and had some difficulties understanding them, since I found no documentation or comments.

Since you asked for feedback and suggestions, I will gladly take the opportunity: 

Having some comments in the yaml configs, for example, would help, I think. These could include the full name of the dataset, the name of/link to the corresponding publication/repository, or some other reference that quickly associates a configuration entry with something that you can find via web search. The same goes for the code of the methods: Why not just add a reference to the paper as a comment to each class? At the moment, I have to look at the class name of the detector, go to the leader board website (which is awesome, btw.), and find the corresponding publication there, which is a bit tedious. 

I saw that people were working on descriptions of the methods/detectors in the wiki, which is a good idea, but why not include the descriptions in the code? This would also serve as documentation (or maybe I am missing the point of the Wiki?). Datasets could be included (with a short summary of size and content) as well (in code or wiki). 

It might also be a good idea to create a sphinx documentation and host it, for example, on read-the-docs. Also, you could, for example, use [Hydra](https://hydra.cc/) for the configuration.  

So in my opinion, in terms of documentation of code, people might appreciate something more in the style of [pytorch-ood](https://pytorch-ood.readthedocs.io/en/latest/detector.html) (which I maintain, so I am of course biased 🙂).  

These are just suggestions. I appreciate your work and I fully understand that documentation is not your top priority (compared to benchmarking). But I think both could help to advance OOD detection as a field.

**Comment by zjysteven** [comment]
Oh greetings to the pytorch-ood team :wave: ! And thank you very much for all the detailed suggestions; they are definitely things that we could improve. I will let other collaborators know and work on the documentation. If you have any further ideas/thoughts maybe on improving the field together, don't hesitate to let us know as we are always open to potential collaboration.
